# Ensures that docker image is present

- name: Ensure openHAB repository is present on self-build
  git:
    repo: "{{ openhab_container_image_self_build_repo }}"
    dest: "{{ openhab_docker_src_files_path }}"
    force: "yes"
  register: openhab_git_pull_results
  when: openhab_docker_image_self_build
  
- name: Ensure openHAB Docker image is built
  docker_image:
    name: "{{ openhab_docker_image }}"
    source: build
    force_source: "{{ openhab_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else openhab_git_pull_results.changed }}"
    build:
      dockerfile: docker/Dockerfile
      path: "{{ openhab_docker_src_files_path }}"
      pull: yes
  when: openhab_docker_image_self_build
  
- name: Ensure openHAB Docker image is pulled
  docker_image:
    name: "{{ openhab_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ openhab_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else openhab_docker_image_force_pull }}"
  when: not openhab_docker_image_self_build
