- name: Ensure config is present
  template:
    src: "{{ role_path }}/templates/configuration.yaml.j2"
    dest: "{{ openhab_data_path }}/configuration.yaml"
    mode: 0644
  notify:
  - Ensure service is restarted
