- import_tasks: "{{ role_path }}/tasks/home-assistant/setup_install.yml"
  when: ha_enabled|bool

- import_tasks: "{{ role_path }}/tasks/home-assistant/setup_uninstall.yml"
  when: "not ha_enabled|bool"
