# Ensures that docker image is present

- name: Ensure home-assistant repository is present on self-build
  git:
    repo: "{{ ha_container_image_self_build_repo }}"
    dest: "{{ ha_docker_src_files_path }}"
    force: "yes"
  register: ha_git_pull_results
  when: ha_docker_image_self_build
  
- name: Ensure home-assistant Docker image is built
  docker_image:
    name: "{{ ha_docker_image }}"
    source: build
    force_source: "{{ ha_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else ha_git_pull_results.changed }}"
    build:
      dockerfile: docker/Dockerfile
      path: "{{ ha_docker_src_files_path }}"
      pull: yes
  when: ha_docker_image_self_build
  
- name: Ensure home-assistant Docker image is pulled
  docker_image:
    name: "{{ ha_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ ha_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else ha_docker_image_force_pull }}"
  when: not ha_docker_image_self_build
