- name: Ensure home-assistant group is created
  group:
    name: "{{ ha_user_groupname }}"
    state: present
  register: ha_group_result

- name: Ensure home-assistant user is created
  user:
    name: "{{ ha_user_username }}"
    state: present
    group: "{{ ha_user_groupname }}"
    home: "{{ ha_base_path }}"
    create_home: no
    system: yes
    shell: "/sbin/nologin"
  register: ha_user_result

- name: Ensure home-assistant paths exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ ha_user_username }}"
    group: "{{ ha_user_groupname }}"
  with_items:
    - { path: "{{ ha_docker_src_files_path }}", when: "{{ ha_docker_image_self_build }}" }
    - { path: "{{ ha_config_path }}", when: true}
    - { path: "{{ ha_data_path }}", when: true}
  when: "item.when"
