# Ensures that docker image is present

- name: Ensure zigbee2mqtt repository is present on self-build
  git:
    repo: "{{ zigbee2mqtt_container_image_self_build_repo }}"
    dest: "{{ zigbee2mqtt_docker_src_files_path }}"
    force: "yes"
  register: zigbee2mqtt_git_pull_results
  when: zigbee2mqtt_docker_image_self_build
  
- name: Ensure zigbee2mqtt Docker image is built
  docker_image:
    name: "{{ zigbee2mqtt_docker_image }}"
    source: build
    force_source: "{{ zigbee2mqtt_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else zigbee2mqttgit_pull_results.changed }}"
    build:
      dockerfile: docker/Dockerfile
      path: "{{ zigbee2mqtt_docker_src_files_path }}"
      pull: yes
  when: zigbee2mqtt_docker_image_self_build
  
- name: Ensure zigbee2mqtt Docker image is pulled
  docker_image:
    name: "{{ zigbee2mqtt_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ zigbee2mqtt_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else zigbee2mqtt_docker_image_force_pull }}"
  when: not zigbee2mqtt_docker_image_self_build
