- name: Ensure zigbee2mqtt group is created
  group:
    name: "{{ zigbee2mqtt_user_groupname }}"
    state: present

- name: Ensure zigbee2mqtt user is created
  user:
    name: "{{ zigbee2mqtt_user_username }}"
    state: present
    group: "{{ zigbee2mqtt_user_groupname }}"
    home: "{{ zigbee2mqtt_base_path }}"
    create_home: no
    system: yes

- name: Ensure zigbee2mqtt paths exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ zigbee2mqtt_user_username }}"
    group: "{{ zigbee2mqtt_user_groupname }}"
  with_items:
    - { path: "{{ zigbee2mqtt_docker_src_files_path }}", when: "{{ zigbee2mqtt_docker_image_self_build }}" }
    - { path: "{{ zigbee2mqtt_data_path }}", when: true}
  when: "item.when"
